### ISSUE TITLE
AttributeError: '_FileInFile' object has no attribute 'fileno'

### ISSUE THREAD

**Issue by piskvorky** [pauldmccarthy/indexed_gzip#117]
When I process a file-like object (nested `.tgz` read from network, not a local file) opened like so:

```python
IndexedGzipFile(fileobj=fileobj, mode='rb', auto_build=True, spacing=1024**2)
```

I get this error:

```
File "indexed_gzip/indexed_gzip.pyx", line 148, in indexed_gzip.indexed_gzip.IndexedGzipFile.__init__
File "indexed_gzip/indexed_gzip.pyx", line 391, in indexed_gzip.indexed_gzip._IndexedGzipFile.__init__
AttributeError: '_FileInFile' object has no attribute 'fileno'
```

Looking at that code:

https://github.com/pauldmccarthy/indexed_gzip/blob/42557f6146e8ca7ad7858b4012c57b800fd5a42f/indexed_gzip/indexed_gzip.pyx#L381-L393

What is that `fileobj.fileno()` call about?

**Comment by pauldmccarthy** [comment]
Hi @piskvorky, the `zran.c` module is able to work with either a Python file-like object, or (preferentially) with a raw file descriptor - this bit of code attempts to retrieve the underlying file descriptor from a file-like, setting it to `NULL` if it is unable to do so.

It looks like the  `_FileInFile` class you are using doesn't implement the [`fileno()` method](https://docs.python.org/3/library/io.html#io.IOBase.fileno). Additionally, my code should technically be checking for an `OSError` rather than an `UnsuppportedOperation` (although every implementation I've come across to date will raise the latter).

**Comment by pauldmccarthy** [comment]
@piskvorky Expanding the range of ignored exception types sounds like a harmless change to me, so I'm happy to update the logic (see #118)

**Comment by piskvorky** [comment]
Amazing!
