### ISSUE TITLE
export_index without requiring a file

### ISSUE THREAD

**Issue by mxmlnkn** [pauldmccarthy/indexed_gzip#25]
This is just a feature suggestion but I think it'd be nice for `export_index` to be able to return a bytearray with the data instead of requiring a file name or file object.

I use `indexed_gzip` as a dependency in [`ratarmount`](https://github.com/mxmlnkn/ratarmount).
There, I create a temporary file, which I give to `export_index`, then I read it out and write the contents into a SQLite database.

Currently, I've got one [issue](https://github.com/mxmlnkn/ratarmount/issues/21), where `export_index` fails for some reason I can't reproduce.

I think it would be helpful if `export_index` would be able to return a bytearray directly instead of going the roundabout and seemingly error-prone way of the file system.

I'd also welcome if you have another idea why `export_index` fails but looking at the source code it only seems to be `fwrite` calls, which might trigger the -1 error code. The code looks like this:

```
# Transparently force index to be built if not already done so. build_full_index was buggy for me.
# Seeking from end not supported, so we have to read the whole data in in a loop
while self.tarFile.read( 1024*1024 ):
    pass
self.tarFile.export_index( filename = gzindex )
```

Unfortunately, I forgot what bug I had with `build_full_index` and seeing #18, might that missing call to `build_index` actually be the problem or has that issue with the missing index creation on reads been fixed?

**Comment by pauldmccarthy** [comment]
Sorry for the delay, I've been away from my computer. So it sounds like the original problem was not due to a bug in `indexed_gzip`?

Unfortunately, modifying the `IndexedGzipFile.export_index` method to return a byte array would not be straightforward as it results in a call to the underlying `zran_export_index` function which expects a `FILE *` struct (and hence a real file). 

The `zran_export_index` function could be modified to write to an in-memory array, but I honestly don't see the value in unnecessarily complicating that function when the alternative (write to a temporary file, read back in) is so trivial, and should be robust on any platform.

**Comment by pauldmccarthy** [comment]
The only way I can think of to get at the index data without saving it to the file system is to use a [named pipe](https://docs.python.org/3.6/library/os.html#os.mkfifo) (which still requires an entry to be created on the file system, but no data). The following hacky code does what you want:

```python
import os 
import threading 
import indexed_gzip as igzip 
 
gzf = igzip.IndexedGzipFile('test.fa.gz') 
gzf.build_full_index() 
 
fifo = 'myfifo' 
result = [] 
 
os.mkfifo(fifo) 
 
def read_index(fifo, result): 
    with open('myfifo', 'rb') as f: 
        result.append(f.read()) 
 
rt = threading.Thread(target=read_index, args=(fifo, result)) 
 
rt.start() 
 
with open(fifo, 'wb') as f:
    gzf.export_index(fileobj=f) 
 
rt.join() 
 
index_data = result[0] 
os.remove(fifo)
```

**Comment by mxmlnkn** [comment]
The named pipe might be a good idea to save "peak" disk space. Some tests for the index size:

 - `aclImdb_v1.tar.gz` (81MiB compressed, 284MiB uncompressed) -> 2.2MiB index (2.7% ~ 1/37th of the original, 1/130th compared to uncompressed)
 - `flower_photos.tar.gz` (219MiB compressed, 225MiB uncompressed) -> 1.8MiB index (0.8% ~ 1/125th of the original, 1/128th compared to uncompressed)
 - `CTU-13-Dataset.tar.gz` (2419MiB compressed, 74.3GiB uncompressed) -> 400MiB index (16.5% ~ 1/6th of the original, 1/190th compared to uncompressed)

I guess because the "savepoints" are chosen every 4MiB of *uncompressed* data if I understand this correctly(?), the index files can indeed grow very large. This is kind of a problem as it also has to fit in RAM :/ Could this be changed to be adjustable or calculated in respected to compressed size in order to influence the space to seek time trade-off?

IndexedBzip2:
 
 - `aclImdb_v1.tar.gz` (81MiB compressed, 284MiB uncompressed) -> 4176B index (1/13911th of the original, 261 block offset pairs, on average 217kiB per block)
 - `flower_photos.tar.gz` (219MiB compressed, 225MiB uncompressed) -> 4144 index (1/54922th of the original, 259 block offset pairs, on average 858kiB per block)
 - `CTU-13-Dataset.tar.gz` (2419MiB compressed, 74.3GiB uncompressed) -> 251kiB index (1/7784th of the original, 16038 block offset pairs, on average 122kiB per block)

Imho, the 16% index size compared to the original is much too high for the gzip index. I'd at least want 1 byte per 10k compressed bytes. I actually never benchmarked nor noticed this before this post. Looking into the index file it seems like it contains quite a lot of the uncompressed data, I assume some kind of state buffer. For bz2, I only need to store two 64-bit numbers per block. Compared to a state which seemingly can be ~4KiB and larger required for `indexed_gzip`.

> Sorry for the delay, I've been away from my computer. So it sounds like the original problem was not due to a bug in `indexed_gzip`?

I only know that it got to work after changing the file location from tmp to somewhere else, so I don't think it was an issue with `indexed_gzip`. Looking at the code there doesn't seem much that could go wrong except for the filesystem running full on some write.

> Unfortunately, modifying the `IndexedGzipFile.export_index` method to return a byte array would not be straightforward as it results in a call to the underlying `zran_export_index` function which expects a `FILE *` struct (and hence a real file).

An overload for `zran_export_index` could be written up but I see that this would be a major API change and work to do. Also, I see that it might be a problem as an additional step has to be added to precalculate the correct buffer size.

> The `zran_export_index` function could be modified to write to an in-memory array, but I honestly don't see the value in unnecessarily complicating that function when the alternative (write to a temporary file, read back in) is so trivial, and should be robust on any platform.

I can only restate that I think that file based output seems more restrictive to me than a simple buffer which then could be written to a file by the caller. With file based output there always is another layer of complexity like what to do on read-only file systems?

Then again, as I have to write a SQLite file anyway I'll just try to write the `indexed_gzip` output to a compressed file in the same location, so it would be fine with me to close this issue.

**Comment by pauldmccarthy** [comment]
> I guess because the "savepoints" are chosen every 4MiB of uncompressed data if I understand this correctly(?), the index files can indeed grow very large. This is kind of a problem as it also has to fit in RAM :/ Could this be changed to be adjustable or calculated in respected to compressed size in order to influence the space to seek time trade-off?

Yes, the spacing is defined relative to the uncompressed data stream. You can adjust the seek point spacing using the `spacing` argument when creating an `IndexedGzipFile`. Increasing the spacing will reduce the number of seek points and thus the size of the index, at the cost of increasing the average seek time. It would be difficult to automatically calculate a suitable spacing for a given file, as there's no way of knowing how big the uncompressed data is until you decompress it all<sup>*</sup>.

<sup>*</sup>The uncompressed size modulo 2^32 is stored in the last 4 bytes of a `gzip` file, so is only useful for files with < 4GiB uncompressed data. Nor is it possible to estimate uncompressed size from compressed size - I've had to deal with extremely sparse 4D volumetric files which are ~40MB compressed, but ~20GB uncompressed!

> Looking into the index file it seems like it contains quite a lot of the uncompressed data, I assume some kind of state buffer. For bz2, I only need to store two 64-bit numbers per block. Compared to a state which seemingly can be ~4KiB and larger required for indexed_gzip.

It is necessary to store 32KiB of uncompressed data for each seek point, in order to initialise decompression from that point. There's no way around this - `bzip2` is simply a superior format to `gzip` for random access.

> I can only restate that I think that file based output seems more restrictive to me than a simple buffer which then could be written to a file by the caller. With file based output there always is another layer of complexity like what to do on read-only file systems?

If the index file format had been designed as a straight dump of the `zran_index_t` / `zran_point_t` structs, then this would be trivial (as the data would already be present in memory, notwithstanding endianness assumptions). But the file format is slightly different from the in-memory format, so the export routine is necessary, and to support writing to either a file or an in-memory buffer would require duplicating the export code (or abstracting out the various calls to `fwrite`/`memcpy`). 

I'm currently of the opinion that this (e.g. running on a read-only file system) is too niche a use-case to warrant modifying the export. But I'm happy to reconsider, or review a PR, if this ends up being a real show-stopper for you.

**Comment by mxmlnkn** [comment]
Ok, thank you. I overlooked the spacing argument, this helps. I'll keep the PR in mind but I think I'll first work with reusing locations I have to write to anyways.
