### ISSUE TITLE
Add support for SEEK_END

### ISSUE THREAD

**Issue by mxmlnkn** [pauldmccarthy/indexed_gzip#36]
IndexedGzipFile.seek does not support SEEK_END. I don't see why SEEK_SET is support but not seek end. Shouldn't the total decompressed file length be available if there is an index? And if not just force building the index first.

**Comment by MarkWieczorek** [comment]
I too would like to ask that support be added for SEEK_END, of the form: `f.seek(0, os.SEEK_END)`. 

The reason for doing this is that I would like to open a large gzipped text file, and then read only the last line of the file. One way to do this is to seek to the end, and then read backwards until you get to a new line. Doing this with gzip itself is prohibitively slow....

Here is an example of the problem:
```
f.seek(0, os.SEEK_END)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-8-ebb484f88f63> in <module>
----> 1 f.seek(0, os.SEEK_END)

indexed_gzip/indexed_gzip.pyx in indexed_gzip.indexed_gzip._IndexedGzipFile.seek()

ValueError: Seek from end not supported
```

**Comment by pauldmccarthy** [comment]
@mxmlnkn the reason that I didn't implement `SEEK_END` was because I never had the need for it. However, conditional support for it should be a trivial change to `zran_seek`, e.g. (pseudo-ish code):
```
if (whence == SEEK_END && index->uncompressed_size == 0) {
    goto fail_index_not_built;
}
if (whence == SEEK_END) {
   offset = offset - index->uncompressed_size
}
else if (whence == SEEK_CUR) {
...
}
...
```

@MarkWieczorek What you are asking for is not possible with the gzip file format - in order to read the last byte of a gzip file, you must decompress the entire file - there is no way around this. Personally, I would not recommend using the gzip file format if you have the choice - there are better compression formats out there which provide better support for random access.

**Comment by MarkWieczorek** [comment]
I understand that I need to decompress the entire file: I have no other choice! 
 
The problem is that if I seek backwards from the end of the file using gzip, I think that the file gets decompressed several times: Doing this is many times slower than just using readline() until arriving at the end of the file...

**Comment by mxmlnkn** [comment]
@MarkWieczorek If you only want the the last line and knowing that you need to decompress it first anyways, you could simply adjust your find-last-line algorithm. You only have to keep track of the current line while decompressing and voilà.

1. Decompress one character and test for end-of-file
2. If character is not a new line, append it to the current line buffer and go to 1.
3. If character is a new line and we are not at the end of the file, clear the current line buffer and go to 1
4. If character is new line and we are at the end of the file, your result and the last line of the file is in the current line buffer and you are done.

I for my part, basically needed the SEEK_END to get the file size. My [workaround](https://github.com/mxmlnkn/ratarmount/commit/27c8ca396adc3fdb53849349af127e3a998d611a#diff-e8cb0028eb64dd94f04fbefc6c7cc303R502-R504) now is:
```python
while fileObject.read( 1024*1024 ):
    self._updateProgressBar( progressBar, fileObject )
fileSize = fileObject.tell()
```
It has the nice side-effect that I can show a progress bar, so I wouldn't even need the SEEK_END currently anymore. I just opened the MR for completeness sake.

**Comment by mathieuboudreau** [comment]
p.s. just to let you know that this broke loading images for our AxonDeepSeg addon. Stoyan will be opening an issue about it.

**Comment by pauldmccarthy** [comment]
Sigh. Reproduced. I'll beat you to opening a new issue.
