### ISSUE TITLE
Exporting/importing indexes to/from a file

### ISSUE THREAD

**Issue by ozars** [pauldmccarthy/indexed_gzip#7]
Hello,

I was looking for a way to export gzip file indexes to a file and import it for later invocations of IndexedGzip class. That is, I want to save created indexes to a file and load it later. I looked into the documentation and code, but I couldn't figure it out. Can I do it somehow?

In my case gzip files are historical, i.e. they don't change at all. It makes sense for me to precompute 32KB gzip parameters per ~1MB blocks. Then, I plan to use binary search to random access records on gzip file by looking at those index files.

Thanks.

**Comment by pauldmccarthy** [comment]
This is a good idea - it's something that I had thought about, but haven't gotten around to doing yet (I have no need for it personally).

I'll try and find some time to have a play this week. Initial inspection suggests that I might be able to simply dump out the contents of the `zran_index_t` struct (at the C level, not in Python), so it will hopefully not be too difficult.

**Comment by ozars** [comment]
Thanks for the prompt answer.

I'm going through the code at the moment. These are what I inferred from the code so far:

It may be better to have a python interface with two methods like `get_current_seek_point()` and `add_seek_point(...)`. This gives explicit control to the user about how to serialize/deserialize seek points as well as where to create them. So, it takes burden of serializing and deserializing `zran_index_t`. A flag like `ZRAN_MANUAL_BUILD` to disable automatic creation of checkpoints for every `spacing` bytes would be really useful as well.

 `add_seek_point` needs to call `_zran_add_point`. Since index list is an ordered list, it should give an error if user tries to add a point with offset lower than the last point.

`get_current_seek_point()` can return a tuple consisting of elements of `zran_point_t`. It makes a call to `_zran_get_point_at` to return a current point.

I can implement those two functions. I'm guessing `ZRAN_MANUAL_BUILD` should be handled inside `_zran_get_point_with_expand`, not sure though. I can look at it later.

I appreciate if you could correct me if there are mistakes in the logic above. I can implement those two methods, and later manual flag maybe if they make sense. Then I can submit a PR.

**Comment by pauldmccarthy** [comment]
Adding an `add_seek_point` function could work. You will need to use the `_zran_expand_index` function to do the heavy lifting, rather than calling `_zran_add_point` directly - you can't just add a seek point anywhere - they need to be on a compression block boundary.

To support variable spacing, it might make sense to refactor `_zran_expand_index` so that, rather than using the fixed `zran_index_t.spacing` field, it could be passed a desired spacing.
The only complication that I can see with a variable-sized spacing is that the `zran_read` function won't know how big a read buffer to allocate. This is not a show-stopper however - it is just a minor performance issue.

I don't think it is necessary to add a `ZRAN_MANUAL_BUILD` flag - if `ZRAN_AUTO_BUILD` is not set, then the index won't be automatically built :)

**Comment by ozars** [comment]
> you can't just add a seek point anywhere - they need to be on a compression block boundary.

Got it, thanks... I wanted to align seek points with head of structs in uncompressed data. I realized it is not feasible due to block boundaries then. Variable spacing doesn't make sense in this case.

I can work on import/export if you are busy though. I still need that part. :)

**Comment by pauldmccarthy** [comment]
Well you can place seek points at _approximate_ locations throughout the file. In principle, there is no limit to the size of a compression block (a.k.a. deflate block - ref: http://www.gzip.org/zlib/rfc-deflate.html#overview), but in practice they generally aren't very big. Not sure if that is useful for your needs..
